language: node_js
node_js:
  - "5"
  - "5.1"
notifications:
  email: false
before_script:
  - npm install gulp -g
  - npm install bower -g
  - npm run init
script:
  - npm run test
  - npm run build
cache:
  - node_modules
